### PR TITLE
Version bump to 1.0

### PR DESCRIPTION
**Pull request by vittorio88**
Hello,

Hey I was bored, and decided to update your repository for the latest upstream version of radeontop. I hope this is OK.

I applied the diff from 0.9 to 1.0 to the upstream branch, merged to master, and then updated the debian changelog with the upstream notes. I am unsure about using your email or mine, but, in doubt, I placed mine. If you want I can revert the commit to use yours since you're the maintainer, or you can do it yourself.

- Vittorio

### CODE REVIEW

**Comment by glaubitz** [comment]
Hi!

Thanks for that. I will look into this. But please keep in mind that Debian is in feature freeze now, so I cannot update the package in Debian anyway. I can make an upload to experimental, but that's about all.

Although it is technically possible to upload to Debian unstable, the release team highly discourages any uploads to unstable to keep unstable clean for possible RC bug fixes for Stretch. All package updates have to go through unstable first.

Adrian

**Comment by vittorio88** [comment]
Cool!

I just wanted to get the rock moving. One of the reasons I did this is to add support for Radeon's RX series of cards like my RX470 which isn't detected by v0.9, but is detected by v1.0.

Experimental sounds like a start if the release window for unstable is closed.

Thanks for following up,
Vittorio

**Comment by glaubitz** [comment]
Looks good to me, but you did not import the original upstream source with "--pristine-tar" which means the original tarball is not present in the "pristine-tar" branch. Could you fix that?

Another minor nitpick: You should add yourself for the "debian/*" files in debian/copyright and add the proper year. Just look how it was done for previous versions. And, remember, the commit for debian/changelog should always be the last one.

Oh, and we also have to add the tags for the various upstream versions, those are currently missing. I will fix that locally here and push the tags to github.

Sorry for not getting back earlier, I was very busy last month and I just had time today to start looking at my Debian packages again.

**Comment by vittorio88** [comment]
Hello, sorry for the delay in getting back to you.

It seems to me that you have already done necessary merging, do you require further action on my part, or shall I close this pull-request?

**Comment by glaubitz** [comment]
We can close this pull request. The package is ready as it is, but I am waiting for Debian Stretch to be released before pushing it to unstable.

**Pull request closed without merging**
